CONFIG = {
    "g_lr": 1e-5,
    "d_lr": 1e-5,
    "epochs_num": 250,
    "batch_size": 64,
    "log_each": 5,
    "decay_epoch": 0,
    "save_each": 2,
    "device": "cuda:2",
    "x_dim": 18,
    "z_dim": 16,
    "d_coef": 3,
    "use_gp": False,
    "clip_value": 0.1,
    "lambda": 1,
    "channels": 64,
    "pad_size": 9,
    "g_use_scheduler": False,
    "g_lr_multiplier": 5,
    "g_lr_total_epoch": 200,
    "d_use_scheduler": False,
    "d_lr_multiplier": 5,
    "d_lr_total_epoch": 200,
    "g_beta1": 0,
    "g_beta2": 0.99,
    "d_beta1": 0,
    "d_beta2": 0.99
}
